In [1]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv(r"C:\Users\Decent\Downloads\Pakistan Traffic E-Challan (2018–2026).zip")

# Check shape
print(df.shape)

(827700, 13)

In [2]:
df.head()

,Challan_ID,Date,Year,Month,Day_of_Week,City,Province,Violation_Type,Vehicle_Type,Enforcement_Method,Fine_Amount_PKR,Payment_Status,Amount_Collected_PKR
0,PK-100000,2018-01-01,2018,January,Monday,Peshawar,KPK,Speeding,Motorcycle,Camera,1904,Unpaid,0
1,PK-100001,2018-01-01,2018,January,Monday,Hyderabad,Sindh,Speeding,Car,Camera,2023,Paid,2023
2,PK-100002,2018-01-01,2018,January,Monday,Rawalpindi,Punjab,No Helmet,Rickshaw,Police Officer,1229,Paid,1229
3,PK-100003,2018-01-01,2018,January,Monday,Rawalpindi,Punjab,Mobile Phone Use,Motorcycle,Speed Gun,1732,Paid,1732
4,PK-100004,2018-01-01,2018,January,Monday,Karachi,Sindh,Reckless Driving,Motorcycle,Camera,4899,Paid,4899

In [3]:
# Check all column names
print(df.columns.tolist())

['Challan_ID', 'Date', 'Year', 'Month', 'Day_of_Week', 'City', 'Province', 'Violation_Type', 'Vehicle_Type', 'Enforcement_Method', 'Fine_Amount_PKR', 'Payment_Status', 'Amount_Collected_PKR']

In [4]:
df.dtypes

Challan_ID              object
Date                    object
Year                     int64
Month                   object
Day_of_Week             object
City                    object
Province                object
Violation_Type          object
Vehicle_Type            object
Enforcement_Method      object
Fine_Amount_PKR          int64
Payment_Status          object
Amount_Collected_PKR     int64
dtype: object

In [5]:
df.isnull().sum()

Challan_ID              0
Date                    0
Year                    0
Month                   0
Day_of_Week             0
City                    0
Province                0
Violation_Type          0
Vehicle_Type            0
Enforcement_Method      0
Fine_Amount_PKR         0
Payment_Status          0
Amount_Collected_PKR    0
dtype: int64

In [6]:
df.head()

,Challan_ID,Date,Year,Month,Day_of_Week,City,Province,Violation_Type,Vehicle_Type,Enforcement_Method,Fine_Amount_PKR,Payment_Status,Amount_Collected_PKR
0,PK-100000,2018-01-01,2018,January,Monday,Peshawar,KPK,Speeding,Motorcycle,Camera,1904,Unpaid,0
1,PK-100001,2018-01-01,2018,January,Monday,Hyderabad,Sindh,Speeding,Car,Camera,2023,Paid,2023
2,PK-100002,2018-01-01,2018,January,Monday,Rawalpindi,Punjab,No Helmet,Rickshaw,Police Officer,1229,Paid,1229
3,PK-100003,2018-01-01,2018,January,Monday,Rawalpindi,Punjab,Mobile Phone Use,Motorcycle,Speed Gun,1732,Paid,1732
4,PK-100004,2018-01-01,2018,January,Monday,Karachi,Sindh,Reckless Driving,Motorcycle,Camera,4899,Paid,4899

In [7]:
# Convert Date from object to datetime
df['Date'] = pd.to_datetime(df['Date'])

# Verify
print(df['Date'].dtype)

datetime64[ns]

In [8]:
df.dtypes

Challan_ID                      object
Date                    datetime64[ns]
Year                             int64
Month                           object
Day_of_Week                     object
City                            object
Province                        object
Violation_Type                  object
Vehicle_Type                    object
Enforcement_Method              object
Fine_Amount_PKR                  int64
Payment_Status                  object
Amount_Collected_PKR             int64
dtype: object

In [9]:
# Check unique values
print("Cities:", df['City'].nunique())
print("Provinces:", df['Province'].nunique())
print("Violation Types:", df['Violation_Type'].nunique())
print("Vehicle Types:", df['Vehicle_Type'].nunique())
print("Payment Status:", df['Payment_Status'].unique())
print("Enforcement Method:", df['Enforcement_Method'].unique())

Cities: 10
Provinces: 5
Violation Types: 10
Vehicle Types: 7
Payment Status: ['Unpaid' 'Paid' 'Waived' 'Disputed']
Enforcement Method: ['Camera' 'Police Officer' 'Speed Gun' 'Mobile Unit']

In [10]:
# Check fine amount statistics
print(df['Fine_Amount_PKR'].describe())

count    827700.000000
mean       1831.146514
std        1054.235087
min         300.000000
25%        1073.000000
50%        1667.000000
75%        2291.000000
max        5500.000000
Name: Fine_Amount_PKR, dtype: float64

In [11]:
# Check duplicates
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [12]:
# Check if Challan_ID is unique
print("Total rows:", len(df))
print("Unique Challan IDs:", df['Challan_ID'].nunique())

Total rows: 827700
Unique Challan IDs: 827700

In [13]:
# Check collected amount statistics
print(df['Amount_Collected_PKR'].describe())

# Check unpaid challans
unpaid = df[df['Payment_Status'] == 'Unpaid']['Amount_Collected_PKR'].sum()
print("Total unpaid amount:", unpaid)

count    827700.000000
mean       1006.440414
std        1198.184377
min           0.000000
25%           0.000000
50%         720.000000
75%        1802.000000
max        5500.000000
Name: Amount_Collected_PKR, dtype: float64
Total unpaid amount: 0

In [14]:
# Create fine category
df['Fine_Category'] = pd.cut(
    df['Fine_Amount_PKR'],
    bins=[0, 1000, 2000, 3000, 5500],
    labels=['Low', 'Medium', 'High', 'Very High']
)

print(df['Fine_Category'].value_counts())

Fine_Category
Medium       367527
High         192644
Low          184607
Very High     82922
Name: count, dtype: int64

In [15]:
# Create payment binary column
df['Is_Paid'] = df['Payment_Status'].apply(
    lambda x: 1 if x == 'Paid' else 0
)

print(df['Is_Paid'].value_counts())

Is_Paid
1    455550
0    372150
Name: count, dtype: int64

In [16]:
# Final check
print("Shape:", df.shape)
print("\nColumns:", df.columns.tolist())
print("\nData Types:\n", df.dtypes)

Shape: (827700, 15)

Columns: ['Challan_ID', 'Date', 'Year', 'Month', 'Day_of_Week', 'City', 'Province', 'Violation_Type', 'Vehicle_Type', 'Enforcement_Method', 'Fine_Amount_PKR', 'Payment_Status', 'Amount_Collected_PKR', 'Fine_Category', 'Is_Paid']

Data Types:
 Challan_ID                      object
Date                    datetime64[ns]
Year                             int64
Month                           object
Day_of_Week                     object
City                            object
Province                        object
Violation_Type                  object
Vehicle_Type                    object
Enforcement_Method              object
Fine_Amount_PKR                  int64
Payment_Status                  object
Amount_Collected_PKR             int64
Fine_Category                 category
Is_Paid                          int64
dtype: object

In [18]:
from sqlalchemy import create_engine

# Database credentials
username = "root"
password = "Taimoor123$"
host = "localhost"
port = "3306"
database_name = "traffic_challan_db"

# Create connection engine
engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database_name}")

# Export data to MySQL
df.to_sql(
    name="traffic_challan_data",
    con=engine,
    if_exists="replace",
    index=False
)

print("Data exported successfully to MySQL!")

Data exported successfully to MySQL!